{% set name = "pytest-asyncio" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7496c5977ce88c34379df64a66459fe395cd05543f0a2f837016e7144391fcfb

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - pytest >=5.4.0

test:
  imports:
    - pytest_asyncio
  source_files:
    - src/tests
  requires:
    - pip
    - coverage
    - hypothesis >=5.7.1
  commands:
    - pip check
    - cd src
    # the skip is for docker network issues in CI, reduces coverage from 96
    - coverage run -m pytest -vv -k 'not (unused_port_fixture or unused_port_factory_fixture)'
    - coverage report --fail-under 91

about:
  home: http://github.com/pytest-dev/pytest-asyncio
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  #license_file: LICENSE # License file is missing in package
  summary: Pytest support for asyncio
  doc_url: https://github.com/pytest-dev/pytest-asyncio/blob/master/README.rst
  dev_url: https://github.com/pytest-dev/pytest-asyncio

extra:
  recipe-maintainers:
    - sodre
