{% set name = "pytest-asyncio" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d15463d13f4456e1ead2594520216b225a16f781e144f8fdf6c5bb4667c48b3f

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=77
    - setuptools_scm >=6.2
    - toml
  run:
    - python
    - pytest >=8.2,<9
    - typing-extensions >=4.12 # [py<310]

# Skip the failing tests as they test behavior that changed in pytest 8.x
{% set skip_test = [
  "test_strict_mode_ignores_unmarked_coroutine",
  "test_strict_mode_marked_test_unmarked_fixture_warning",
  "test_strict_mode_marked_test_unmarked_autouse_fixture_warning",
  "test_strict_mode_ignores_unmarked_fixture"
] %}

test:
  source_files:
    - tests
    - pyproject.toml
    - setup.cfg
  imports:
    - pytest_asyncio
  commands:
    - pip check
    - python -c "import pytest_asyncio; assert pytest_asyncio.__version__ == '{{ version }}'"
    - pytest -vv -k 'not ({{ skip_test | join(' or ') }})' # [not win]
    # Skip the failing tests as they test behavior that changed in pytest 8.x
    - pytest --asyncio-mode=auto -v --ignore=tests/modes/test_strict_mode.py # [win]
  requires:
    - pip
    - anyio
    - pytest >=8.2,<9
    - hypothesis >=5.7.1

about:
  home: https://github.com/pytest-dev/pytest-asyncio
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Pytest support for asyncio
  description: |
    pytest-asyncio is a pytest plugin.
    It facilitates testing of code that uses the asyncio library.
  doc_url: https://pytest-asyncio.readthedocs.io
  dev_url: https://github.com/pytest-dev/pytest-asyncio

extra:
  recipe-maintainers:
    - sodre
