{% set name = "pytest-asyncio" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9fac5100fd716cbecf6ef89233e8590a4ad61d729d1732e0a96b84182df1daaf

build:
  number: 1000
  skip: True  # [py2k]
  script: python -m pip install --no-deps --ignore-installed .
  
requirements:
  build:
    - python
    - pip
  run:
    - python
    - pytest >=3.0.6

test:
    imports:
      - pytest_asyncio

about:
  home: http://github.com/pytest-dev/pytest-asyncio
  license: Apache 2.0
  #license_file: LICENSE # License file is missing in package
  summary: 'Pytest support for asyncio'

  dev_url: https://github.com/pytest-dev/pytest-asyncio

extra:
  recipe-maintainers:
    - sodre
