{% set name = "pytest-asyncio" %}
{% set version = "0.21.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name.replace("-", "_") }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
    sha256: d67738fc232b94b326b9d060750beb16e0074210b98dd8b58a5239fa2a154f45
  - folder: src
    url: https://github.com/pytest-dev/pytest-asyncio/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 6ab1c5c0ad8d5aa01d80e51a57b7385fefab4f535bb3db2f6a2a27ad7f59a7c8

build:
  number: 0
  skip: true  # [py<37]
  script: cd dist && {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - toml
    - wheel
  run:
    - python
    - pytest >=7
    - typing_extensions >=3.7.2  # [py<38]

test:
  source_files:
    - src/tests
    - src/setup.cfg
  imports:
    - pytest_asyncio
  requires:
    - pip
    - coverage
    - hypothesis >=5.7.1
    # TODO: add pytest-trio to defaults: test_strict_mode_ignores_trio_fixtures.py requires it
  commands:
    - pip check
    - cd src
    # the skip is for docker network issues in CI, reduces coverage from 96
    - coverage run -m pytest -vv -k 'not (unused_port_fixture or unused_port_factory_fixture or auto_mode_cmdline or test_strict_mode_ignores_trio_fixtures)'  # [not win]
    # 2023/3/16: Skip test on win because of an error 'pytest.PytestDeprecationWarning: @pytest.yield_fixture is deprecated'.
    #- coverage run -m pytest -vv  # [win]
    - coverage report --fail-under 91  # [not win]

about:
  home: https://github.com/pytest-dev/pytest-asyncio
  license: Apache-2.0
  license_family: Apache
  license_file: dist/LICENSE
  summary: Pytest support for asyncio
  description: |
    pytest-asyncio is a pytest plugin.
    It facilitates testing of code that uses the asyncio library.
  doc_url: https://github.com/pytest-dev/pytest-asyncio/blob/master/README.rst
  dev_url: https://github.com/pytest-dev/pytest-asyncio

extra:
  recipe-maintainers:
    - sodre
