{% set name = "pytest-asyncio" %}
{% set version = "0.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name.replace("-", "_") }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: c4df2a697648241ff39e7f0e4a73050b03f123f760673956cf0d72a4990e312f

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - toml
    - wheel
  run:
    - python
    - pytest >=8.2,<9

test:
  source_files:
    - tests
    - pyproject.toml
  imports:
    - pytest_asyncio
  requires:
    - pip
    - hypothesis >=5.7.1
  commands:
    - pip check
    # collected 0 tests on win
    - "pytest -vv -k 'not (unused_port_fixture or unused_port_factory_fixture or auto_mode_cmdline or test_strict_mode_ignores_trio_fixtures)'"  # [not win]

about:
  home: https://github.com/pytest-dev/pytest-asyncio
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Pytest support for asyncio
  description: |
    pytest-asyncio is a pytest plugin.
    It facilitates testing of code that uses the asyncio library.
  doc_url: https://github.com/pytest-dev/pytest-asyncio/blob/master/README.rst
  dev_url: https://github.com/pytest-dev/pytest-asyncio

extra:
  recipe-maintainers:
    - sodre