{% set name = "pytest-asyncio" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 475bd2f3dc0bc11d2463656b3cbaafdbec5a47b47508ea0b329ee693040eebd2

build:
  number: 2
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pytest >=5.4

test:
  imports:
    - pytest_asyncio

about:
  home: http://github.com/pytest-dev/pytest-asyncio
  license: Apache-2.0
  license_file: LICENSE
  #license_file: LICENSE # License file is missing in package
  summary: Pytest support for asyncio

  dev_url: https://github.com/pytest-dev/pytest-asyncio

extra:
  recipe-maintainers:
    - sodre
