travis:
  secure:
    BINSTAR_TOKEN: EIRtNHvyNOLz1HkptbsUbyFeaUA3dTPSh9Ldchp0eS2iiCsJwYTeY/u1MB2x3AXWSswIu3BAPU5F1HHFBZSErXWA5kO5KwZjWADXZA3bAiH60+DL3ySvrGdtZE5h43uwlazWVSh1qcVsttJNhTLtIg6h3ee3T7d4ZB28+q1Vv4lAN1VwuGSzMwIdyfTX1UxA8SdmEvZh2I6FD0HHh2ycxomBT7maPIxWyxkCS872SJD4m7WPp3cyNlD7V8J4A+lnPdL5wics0PudvJya1ijvUr60z4sH8mP0apIDOfABqO+DGAMrIYW3g9Gn1Ve4bQt6IEtzqDUUbjVJNPLsfJX+STy/Vw5Gld5B5Daf2m/jHxEdPh7FhpD3vtW8y+OxQhVvyTYiPjqkBHxTzet3PBzNiiEvtxRFxs6aA6BCqvwNCUVZDFFYky3M6yu6NmnZfo/dp8GiHQHS+jSK7+SHvXibiIAaCORQp4qLJfx5sF4QGRMrrE9SDrpdBvOOpRWOB4QLcJhNkH7zHf1bZFLVptvMGzmrdL9ewBv7L+DBJKM7X0zij7OzRic+0dz1UDLHDpRycnVZv3qrPbLT5CvL9fLHJB9888o3QSOc1aYWy7uVKX//+G+N0LRzu10GprhSeXm0fzYFEXS1dxNyJscN9xGTz0N6fS4ipu8TmfJlutoqhuY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
