travis:
  secure:
    BINSTAR_TOKEN: P0HWBFuRzxO1+qSXIGRHllwkqDaK9+1zFUhMGRd6bOLJPYI1swlwE7Jql9ihnGnblRFeWcIq/7al4g9V3CJwk4jbeOxbqWTbZqeWAIo9QCoWdb5kw4iD0+KEzYRlmh7DP/t46+QfoZRovH6k22JW5iGsRDOA0hcB94944yVax5ZS288x3OG3hspJElckzZ2Z5jy31koBwCgZ9OyoP0WwfWn179/dSQlAOufJTSixJ8uO+EMProTD+PYpBIF2sCppRwke4TwsLdPRnp0rsUoTwIML0zcwJ0c2qqHQqmG17sEhKwL1JfZ2xdqk8Pia9T6inaTfP+YtZtoDegC/dM+kVprPQAU+N1tgHerpActcb/EQs3qYmfPWyWD6AiKU5v+FWAeRit1Nqi8C8sZ11Xp2XSCuGDRT0knlihqEqtJexgUS4tF1kIWzEXUxfCSv365F9l4pWCVDhle2o9VuB7+7+P3IPFzP1skysjPCPK/3Wwrk5ng/NrXoQK6YYKc+uhd2yVcWaVZtbJaTFhgx0o35JmEHYCLH9nhKfCMZGZPG7vDXKdYx1l9k3J4GKSgzVmSX9aQi+a1RFwQJ2eJrO2olR2ZJEh28qcq06x8K2XY/dOCz3lYvAP3cLfVLcIQorEdn6xUs68Sd9ir3Ywa91ihu81gX6iBeNqaoWyQC88Gx/YI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
